### ISSUE TITLE
Paramaterize data ingest scripts to load location specific data

### ISSUE THREAD

**Issue by apoclyps** [apoclyps/my-dev-space#439]
**Is your feature request related to a problem? Please describe.**
At present, the [scripts](https://github.com/apoclyps/my-dev-space/tree/master/scripts) folder contains multiple data sources that are specific to Belfast, Northern Ireland. These scripts should accept a location parameter as environmental config which allows for data to be loaded for additional locations. 

**Describe the solution you'd like**
A parameterized script that accepts a location environmental variable and only receives data for that location. The location payload for the event should be updated to reflect the new location provided to the script.

**Additional context**
* Update event scripts
* Add an appropriate events service test
* Update README

**Comment by alistairjcbrown** [comment]
It may also be worth looking in the `lambdas/` directory for how they're currently pulling data from sources.

For the Farset Labs calendar, location is free (they're all in Belfast). For Meetup.com, the script pulls events from a member, so these are probably a curated list rather than dynamic based on location. For Eventbrite, the script uses the search API for the Belfast address. The lambdas for Meetup.com and Eventbrite both aim to cover all of Northern Ireland by using a location and a radius (60 mile radius around Cookstown).

I think this opens up another question as to what a "location" parameter would look like - is it a city, country, general area?

**Comment by apoclyps** [comment]
In the short term, we could use a `city` as a general indicator as to the proximity of events. e.g. `Belfast` will cover all of Northern Ireland, `Dublin` will cover the South of Ireland,  Glasgow may cover the west of Scotland and Edinburgh covers the East. This will easily allow us to subdomain the site to provide some degree of localized events as a first pass.

In the long term, we will likely use longitude and latitude to produce the ability to query by distance but that will require Elasticsearch to be in place. Some of that initial work will be done here to facilitate this #411.
