### ISSUE TITLE
Cancelled events are listed

### ISSUE THREAD

**Issue by awflwafl** [apoclyps/my-dev-space#660]
**Describe the bug**
Cancelled events are listed.

**To Reproduce**
1. Create a Meetup event
2. Make sure it is listed on Muxer
3. Cancel the Meetup event
4. See that the event is still listed on Muxer

**Expected behavior**

Muxer only lists events that will take place, while cancelled and deleted events are removed from the upcoming events list.

**Screenshots**

Muxer (lists cancelled events) | Meetup (does not list or strikes out cancelled events)
--- | ---
![image](https://user-images.githubusercontent.com/13058213/49926182-e9815080-feb2-11e8-800a-12cfc82d98ba.png) | ![image](https://user-images.githubusercontent.com/13058213/49926187-edad6e00-feb2-11e8-8fc3-bedae43a271a.png)

**Additional context**

These events were cancelled on Meetup in mid-to-late November and are still listed on Muxer in mid December.

**Comment by alistairjcbrown** [comment]
Currently the system just pulls in events. This is also mirrored by the (not yet wired up) lambda setup.

@apoclyps and I had talked about this in the past as a stop gap of perhaps having a "last seen" timestamp on events, and when events are pulled, touching existing events so that this timestamp updates. "last seen" timestamps of a certain age could then be filtered out as they must have been removed from the source system.

Alternatively (and perhaps once the lambda setup is in place) would be to open up the pulling of data to include all types of events (if it doesn't already) and have a more full syncing setup which would make sure to update events correctly if they're deleted.

**Comment by apoclyps** [comment]
Some preliminary work has been implemented to filter soft deleted events from the listing in https://github.com/apoclyps/my-dev-space/pull/442/files. As a first pass, the timestamp approach could be a quick win in those events that have not been modified or seen in x time are soft deleted.

**Comment by awflwafl** [comment]
I'm happy with whatever solution you choose. Ideally, cancelled events would be removed at least at an periodically.
